QUESTIONS = [
   {"question":"ADN có chức năng gì?","options":["A. Lưu trữ thông tin di truyền","B. Vận chuyển O2","C. Tiêu hóa thức ăn","D. Co cơ"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Đơn phân của ADN là gì?","options":["A. Axit amin","B. Nuclêôtit","C. Glucozơ","D. Lipit"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"ARN được tổng hợp theo nguyên tắc nào?","options":["A. Ngẫu nhiên","B. Bổ sung","C. Phân li độc lập","D. Đồng trội"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Gen nằm ở đâu?","options":["A. Tế bào chất","B. Ribôxôm","C. NST","D. Màng sinh chất"],"answer":"C","explanation":"Kiến thức SGK."},
{"question":"Đột biến gen là gì?","options":["A. Thay đổi cấu trúc gen","B. Thay đổi môi trường","C. Tăng trưởng nhanh","D. Sinh sản vô tính"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Hoán vị gen xảy ra ở đâu?","options":["A. Kì đầu I","B. Kì cuối","C. Kì giữa II","D. Kì sau nguyên phân"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Quy luật phân li do ai phát hiện?","options":["A. Darwin","B. Mendel","C. Morgan","D. Watson"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Chọn lọc tự nhiên tác động lên?","options":["A. Kiểu gen","B. Kiểu hình","C. Giao tử","D. ADN trần"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Quần thể là gì?","options":["A. Tập hợp cá thể cùng loài","B. Nhiều loài khác nhau","C. Một cá thể","D. Hệ sinh thái"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Hệ sinh thái gồm?","options":["A. Sinh vật","B. Môi trường","C. Sinh vật và môi trường","D. Đất đá"],"answer":"C","explanation":"Kiến thức SGK."},
{"question":"Phiên mã xảy ra ở đâu?","options":["A. Nhân","B. Ty thể","C. Ribôxôm","D. Lục lạp"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Dịch mã diễn ra tại?","options":["A. Nhân","B. Ribôxôm","C. Màng","D. NST"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Mã di truyền có tính?","options":["A. Đặc hiệu","B. Thay đổi","C. Phụ thuộc loài","D. Ngẫu nhiên"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Đột biến lệch bội là?","options":["A. Thay đổi 1 cặp NST","B. Thay đổi gen","C. Tăng ADN","D. Nhân đôi"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Giao phối ngẫu nhiên làm?","options":["A. Tăng đột biến","B. Thay đổi tần số alen","C. Không đổi tần số alen","D. Tuyệt chủng"],"answer":"C","explanation":"Kiến thức SGK."},
{"question":"Nhân đôi ADN theo nguyên tắc nào?","options":["A. Bổ sung và bán bảo tồn","B. Ngẫu nhiên","C. Phân li độc lập","D. Đồng trội"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Bộ ba mở đầu trên mARN là?","options":["A. UAA","B. AUG","C. UGA","D. UAG"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Enzim tham gia nhân đôi ADN là?","options":["A. ADN polimeraza","B. Amilaza","C. Pepsin","D. Lipaza"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Thường biến là?","options":["A. Biến đổi kiểu hình","B. Biến đổi kiểu gen","C. Đột biến gen","D. Đột biến NST"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Tiến hóa nhỏ là?","options":["A. Hình thành loài mới","B. Biến đổi tần số alen","C. Tuyệt chủng","D. Phát sinh sự sống"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Nhóm sinh vật sản xuất là?","options":["A. Thực vật","B. Động vật","C. Vi khuẩn phân hủy","D. Nấm"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Chuỗi thức ăn bắt đầu từ?","options":["A. Sinh vật sản xuất","B. Sinh vật tiêu thụ","C. Phân giải","D. Con người"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Giao phối gần gây?","options":["A. Ưu thế lai","B. Thoái hóa giống","C. Tăng biến dị","D. Tăng alen trội"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Ưu thế lai biểu hiện ở?","options":["A. F1","B. P","C. F2","D. Giao tử"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Bằng chứng giải phẫu so sánh là?","options":["A. Cơ quan tương đồng","B. ADN","C. Hóa thạch","D. Địa lí"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Nhân tố tiến hóa cơ bản là?","options":["A. Đột biến","B. Hô hấp","C. Quang hợp","D. Tiêu hóa"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Cách li sinh sản dẫn đến?","options":["A. Hình thành loài","B. Tăng số lượng","C. Đột biến","D. Tuyệt chủng"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"ADN gồm mấy mạch?","options":["A. 1","B. 2","C. 3","D. 4"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"NST co xoắn cực đại ở kì?","options":["A. Kì giữa","B. Kì đầu","C. Kì cuối","D. Trung gian"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Đột biến chuyển đoạn là?","options":["A. Trao đổi đoạn NST","B. Mất gen","C. Thêm gen","D. Nhân đôi gen"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Sinh vật tiêu thụ bậc 1 là?","options":["A. Ăn thực vật","B. Ăn thịt","C. Phân giải","D. Quang hợp"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Tháp sinh thái thể hiện?","options":["A. Số lượng và năng lượng","B. ADN","C. NST","D. Gen"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Mã di truyền có tính phổ biến nghĩa là?","options":["A. Chung cho nhiều loài","B. Riêng từng loài","C. Thay đổi","D. Ngẫu nhiên"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Đột biến điểm xảy ra ở?","options":["A. 1 cặp nu","B. Nhiều NST","C. Cả bộ gen","D. Quần thể"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Phân li độc lập xảy ra khi?","options":["A. Gen trên NST khác nhau","B. Cùng NST","C. Liên kết","D. Đồng trội"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Di truyền liên kết do ai phát hiện?","options":["A. Morgan","B. Mendel","C. Darwin","D. Lamark"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Gen đa hiệu là?","options":["A. 1 gen ảnh hưởng nhiều tính trạng","B. Nhiều gen 1 tính trạng","C. Không ảnh hưởng","D. Trội hoàn toàn"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Cân bằng di truyền tuân theo định luật?","options":["A. Hardy-Weinberg","B. Mendel","C. Morgan","D. Darwin"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Phân giải vật chất do?","options":["A. Vi khuẩn, nấm","B. Thực vật","C. Động vật","D. Con người"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Tiến hóa lớn là?","options":["A. Hình thành nhóm phân loại trên loài","B. Thay đổi alen","C. Đột biến gen","D. Giao phối"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Alen là?","options":["A. Các dạng khác nhau của gen","B. NST","C. ADN","D. Protein"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Kiểu gen là?","options":["A. Tổ hợp alen","B. Biểu hiện ngoài","C. Môi trường","D. Sinh cảnh"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Kiểu hình là?","options":["A. Biểu hiện ra ngoài","B. ADN","C. NST","D. Gen"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Đột biến mất đoạn thường?","options":["A. Gây hại","B. Có lợi","C. Trung tính","D. Không ảnh hưởng"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Di nhập gen làm?","options":["A. Thay đổi tần số alen","B. Không đổi","C. Tuyệt chủng","D. Tăng kích thước"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Chọn lọc nhân tạo do?","options":["A. Con người","B. Tự nhiên","C. Môi trường","D. Đột biến"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Sinh cảnh là?","options":["A. Nơi sống của loài","B. Quần thể","C. Hệ sinh thái","D. Sinh quyển"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Cạnh tranh khác loài dẫn đến?","options":["A. Phân li ổ sinh thái","B. Tuyệt chủng ngay","C. Không ảnh hưởng","D. Đồng trội"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Tự thụ phấn lâu dài làm?","options":["A. Tăng đồng hợp","B. Tăng dị hợp","C. Không đổi","D. Đột biến"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Hóa thạch là bằng chứng?","options":["A. Tiến hóa","B. Sinh thái","C. Di truyền","D. Công nghệ"],"answer":"A","explanation":"Kiến thức SGK."},

{"question":"Operon là mô hình điều hòa ở sinh vật nào?","options":["A. Sinh vật nhân thực","B. Vi khuẩn","C. Thực vật","D. Động vật"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Enzim tháo xoắn ADN là?","options":["A. Helicaza","B. ADN polimeraza","C. Ligaza","D. Restrictaza"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Bộ ba kết thúc không mã hóa axit amin là?","options":["A. AUG","B. UGG","C. UAA","D. AUA"],"answer":"C","explanation":"Kiến thức SGK."},
{"question":"Đột biến đảo đoạn xảy ra ở?","options":["A. Gen","B. NST","C. Tế bào chất","D. Ribôxôm"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Gen cấu trúc có chức năng?","options":["A. Điều hòa","B. Tổng hợp protein","C. Nhân đôi","D. Phiên mã ngược"],"answer":"B","explanation":"Kiến thức SGK."},

{"question":"NST tương đồng là?","options":["A. Giống nhau về hình dạng, kích thước","B. Giống hoàn toàn alen","C. Khác nguồn gốc","D. Không bắt cặp"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Sự nhân đôi NST diễn ra ở kì nào?","options":["A. Trung gian","B. Kì đầu","C. Kì giữa","D. Kì sau"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Tần số alen của quần thể thay đổi do?","options":["A. Đột biến","B. Hô hấp","C. Tiêu hóa","D. Quang hợp"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Quần xã là gì?","options":["A. Tập hợp nhiều quần thể khác loài","B. Một quần thể","C. Một cá thể","D. Một gen"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Dòng năng lượng trong hệ sinh thái có đặc điểm?","options":["A. Tuần hoàn","B. Một chiều","C. Ngẫu nhiên","D. Không đổi"],"answer":"B","explanation":"Kiến thức SGK."},

{"question":"Di truyền ngoài nhân liên quan đến?","options":["A. ADN ti thể","B. NST thường","C. NST giới tính","D. Gen nhân"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Tự nhân đôi ADN diễn ra theo cơ chế?","options":["A. Bán bảo tồn","B. Toàn bảo tồn","C. Ngẫu nhiên","D. Đồng trội"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Ưu thế lai đạt cao nhất ở?","options":["A. F1","B. F2","C. P","D. F3"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Nhân tố ngẫu nhiên ảnh hưởng mạnh ở?","options":["A. Quần thể lớn","B. Quần thể nhỏ","C. Hệ sinh thái","D. Sinh quyển"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Cách li địa lí dẫn đến?","options":["A. Hình thành loài mới","B. Tăng giao phối","C. Giảm biến dị","D. Tuyệt chủng ngay"],"answer":"A","explanation":"Kiến thức SGK."},

{"question":"Thành phần cấu tạo của nuclêôtit gồm?","options":["A. Đường, bazơ nitơ, nhóm photphat","B. Axit amin, đường","C. Protein, lipit","D. Glucozơ, axit béo"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Liên kết giữa các nuclêôtit trên cùng một mạch ADN là?","options":["A. Hiđrô","B. Peptit","C. Photphodieste","D. Ion"],"answer":"C","explanation":"Kiến thức SGK."},
{"question":"Tính trạng do nhiều gen quy định gọi là?","options":["A. Gen đa alen","B. Tương tác gen","C. Di truyền liên kết","D. Đồng trội"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Đột biến thay thế một cặp nu có thể gây?","options":["A. Thay đổi một axit amin","B. Mất cả gen","C. Mất NST","D. Tăng bộ NST"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Môi trường sống của quần thể gọi là?","options":["A. Ổ sinh thái","B. Quần xã","C. Hệ sinh thái","D. Sinh quyển"],"answer":"A","explanation":"Kiến thức SGK."},

{"question":"Quan hệ hỗ trợ giữa các cá thể cùng loài có ý nghĩa?","options":["A. Tăng khả năng sống sót","B. Giảm sinh sản","C. Gây tuyệt chủng","D. Không ảnh hưởng"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Sinh vật phân giải có vai trò?","options":["A. Phân hủy chất hữu cơ","B. Quang hợp","C. Săn mồi","D. Thụ phấn"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Biến dị tổ hợp xuất hiện do?","options":["A. Đột biến","B. Tái tổ hợp gen","C. Thường biến","D. Môi trường"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Hiện tượng đa bội phổ biến ở?","options":["A. Động vật","B. Thực vật","C. Vi khuẩn","D. Nấm men"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Đột biến gen cung cấp nguyên liệu cho?","options":["A. Tiến hóa","B. Hô hấp","C. Quang hợp","D. Tiêu hóa"],"answer":"A","explanation":"Kiến thức SGK."},

{"question":"Phát sinh sự sống trải qua các giai đoạn?","options":["A. Tiến hóa hóa học và sinh học","B. Hô hấp","C. Quang hợp","D. Đột biến"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Mã di truyền có tính thoái hóa nghĩa là?","options":["A. Một axit amin do nhiều bộ ba mã hóa","B. Một bộ ba mã hóa nhiều axit amin","C. Thay đổi theo loài","D. Không đặc hiệu"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Tính trạng trội hoàn toàn biểu hiện khi?","options":["A. Đồng hợp trội","B. Dị hợp","C. Đồng hợp lặn","D. Cả A và B"],"answer":"D","explanation":"Kiến thức SGK."},
{"question":"Gen nằm trên NST giới tính gọi là?","options":["A. Gen thường","B. Gen liên kết giới tính","C. Gen đa hiệu","D. Gen trội"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Sự phân li của NST xảy ra ở kì?","options":["A. Kì sau","B. Kì đầu","C. Trung gian","D. Kì cuối"],"answer":"A","explanation":"Kiến thức SGK."},

{"question":"Chọn lọc tự nhiên có vai trò?","options":["A. Định hướng tiến hóa","B. Tạo đột biến","C. Nhân đôi ADN","D. Tổng hợp protein"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Cấu trúc không gian của protein do?","options":["A. Trình tự axit amin","B. Môi trường","C. NST","D. Lipit"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Đột biến thêm một cặp nu thuộc dạng?","options":["A. Thay thế","B. Thêm","C. Mất","D. Đảo"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Quan hệ kí sinh là?","options":["A. Một loài có lợi, một loài có hại","B. Cả hai có lợi","C. Cả hai có hại","D. Không ảnh hưởng"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Tháp năng lượng có đặc điểm?","options":["A. Luôn dạng chuẩn","B. Có thể đảo ngược","C. Không thay đổi","D. Không tồn tại"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"ADN có cấu trúc dạng gì?","options":["A. Chuỗi đơn","B. Xoắn kép","C. Vòng đơn","D. Thẳng"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Bazơ nitơ nào không có trong ARN?","options":["A. A","B. T","C. G","D. X"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Quá trình tổng hợp ARN từ ADN gọi là?","options":["A. Nhân đôi","B. Phiên mã","C. Dịch mã","D. Đột biến"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Ribôxôm có chức năng?","options":["A. Nhân đôi ADN","B. Tổng hợp protein","C. Phân giải tinh bột","D. Vận chuyển O2"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Đột biến cấu trúc NST gồm?","options":["A. Mất, lặp, đảo, chuyển đoạn","B. Thay thế nu","C. Thêm nu","D. Nhân đôi gen"],"answer":"A","explanation":"Kiến thức SGK."},

{"question":"Tần số kiểu gen phụ thuộc vào?","options":["A. Tần số alen","B. Môi trường","C. Thức ăn","D. Nhiệt độ"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Hiện tượng gen trội át gen lặn gọi là?","options":["A. Đồng trội","B. Trội hoàn toàn","C. Tương tác","D. Hoán vị"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Tương tác bổ sung là dạng?","options":["A. Một gen nhiều tính trạng","B. Nhiều gen một tính trạng","C. Di truyền giới tính","D. Liên kết gen"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Quần thể cân bằng khi?","options":["A. Không có đột biến","B. Tần số alen không đổi","C. Không sinh sản","D. Không chọn lọc"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Sinh quyển là?","options":["A. Toàn bộ sinh vật trên Trái Đất","B. Một quần xã","C. Một quần thể","D. Một hệ sinh thái"],"answer":"A","explanation":"Kiến thức SGK."},

{"question":"Chuỗi polipeptit được hình thành ở?","options":["A. Nhân","B. Ribôxôm","C. Ty thể","D. Lục lạp"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Đột biến lệch bội thường gây?","options":["A. Ít ảnh hưởng","B. Rối loạn phát triển","C. Tăng sinh sản","D. Có lợi"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Đa bội lẻ thường?","options":["A. Sinh sản hữu tính bình thường","B. Bất thụ","C. Tăng sinh sản","D. Không ảnh hưởng"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Chọn lọc tự nhiên giữ lại?","options":["A. Biến dị có lợi","B. Biến dị có hại","C. Tất cả biến dị","D. Không biến dị"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Hệ sinh thái bền vững khi?","options":["A. Mất cân bằng","B. Đa dạng sinh học cao","C. Ít loài","D. Không phân giải"],"answer":"B","explanation":"Kiến thức SGK."},

{"question":"Mã di truyền gồm bao nhiêu bộ ba?","options":["A. 16","B. 32","C. 64","D. 128"],"answer":"C","explanation":"Kiến thức SGK."},
{"question":"Nuclêôtit liên kết với nhau bằng?","options":["A. Liên kết hiđrô","B. Liên kết peptit","C. Liên kết photphodieste","D. Liên kết ion"],"answer":"C","explanation":"Kiến thức SGK."},
{"question":"Gen điều hòa có vai trò?","options":["A. Tổng hợp protein cấu trúc","B. Điều khiển hoạt động gen khác","C. Nhân đôi ADN","D. Tạo đột biến"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Biến động số lượng cá thể theo chu kì do?","options":["A. Mùa vụ","B. Đột biến","C. Gen","D. NST"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Quan hệ cộng sinh là?","options":["A. Hai loài cùng có lợi","B. Một có lợi một hại","C. Cạnh tranh","D. Không liên quan"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Quá trình dịch mã kết thúc khi?","options":["A. Gặp bộ ba kết thúc","B. Hết axit amin","C. Ribôxôm tách đôi","D. ADN nhân đôi"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Loại ARN vận chuyển axit amin là?","options":["A. mARN","B. tARN","C. rARN","D. miARN"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Gen phân mảnh phổ biến ở?","options":["A. Sinh vật nhân sơ","B. Sinh vật nhân thực","C. Vi khuẩn","D. Virus"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Đột biến có lợi có vai trò?","options":["A. Tăng thích nghi","B. Gây chết","C. Không di truyền","D. Giảm đa dạng"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Kích thước quần thể tối thiểu nhằm?","options":["A. Tránh tuyệt chủng","B. Tăng đột biến","C. Giảm sinh sản","D. Giảm đa dạng"],"answer":"A","explanation":"Kiến thức SGK."},

{"question":"Tự thụ phấn qua nhiều thế hệ làm?","options":["A. Tăng dị hợp","B. Tăng đồng hợp","C. Không đổi","D. Tăng biến dị tổ hợp"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Hiện tượng đa alen là?","options":["A. Một gen có nhiều alen","B. Nhiều gen một tính trạng","C. Một alen nhiều gen","D. Gen đa hiệu"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Định luật Hardy–Weinberg áp dụng khi?","options":["A. Quần thể lớn, ngẫu phối","B. Có chọn lọc","C. Có đột biến mạnh","D. Di nhập gen"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Sự hình thành loài mới có thể do?","options":["A. Cách li sinh sản","B. Hô hấp","C. Quang hợp","D. Đồng trội"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Ổ sinh thái phản ánh?","options":["A. Vai trò của loài","B. Số lượng cá thể","C. Di truyền","D. Bộ NST"],"answer":"A","explanation":"Kiến thức SGK."},

{"question":"Mối quan hệ vật ăn thịt – con mồi là?","options":["A. Đối kháng","B. Hỗ trợ","C. Cộng sinh","D. Hội sinh"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Tần số alen trong quần thể ký hiệu là?","options":["A. p và q","B. A và a","C. AA và aa","D. N và n"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Enzim nối các đoạn Okazaki là?","options":["A. Ligaza","B. Helicaza","C. Polimeraza","D. Restrictaza"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Đột biến khung đọc do?","options":["A. Thay thế 1 nu","B. Thêm hoặc mất nu","C. Đảo đoạn","D. Chuyển đoạn"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Di truyền tế bào chất chủ yếu theo dòng?","options":["A. Bố","B. Mẹ","C. Cả hai","D. Ngẫu nhiên"],"answer":"B","explanation":"Kiến thức SGK."},

{"question":"Tháp sinh thái có mấy dạng cơ bản?","options":["A. 1","B. 2","C. 3","D. 4"],"answer":"C","explanation":"Kiến thức SGK."},
{"question":"Năng lượng bị hao hụt qua mỗi bậc dinh dưỡng do?","options":["A. Hô hấp","B. Quang hợp","C. Đột biến","D. Nhân đôi"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Quá trình hình thành giao tử diễn ra bằng?","options":["A. Nguyên phân","B. Giảm phân","C. Trực phân","D. Nhân đôi"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Tính đa dạng di truyền giúp quần thể?","options":["A. Thích nghi tốt hơn","B. Tuyệt chủng nhanh","C. Giảm sinh sản","D. Mất cân bằng"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Cơ quan tương tự phản ánh?","options":["A. Nguồn gốc chung","B. Thích nghi giống nhau","C. Cùng chức năng do nguồn gốc khác","D. Không liên quan"],"answer":"C","explanation":"Kiến thức SGK."},

{"question":"Quần thể tăng trưởng theo tiềm năng sinh học có dạng?","options":["A. Chữ S","B. Chữ J","C. Đường thẳng","D. Parabol"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Giới hạn sinh thái là?","options":["A. Khoảng chống chịu","B. Ổ sinh thái","C. Môi trường","D. Hệ sinh thái"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Đột biến NST số lượng gồm?","options":["A. Lệch bội và đa bội","B. Mất đoạn","C. Đảo đoạn","D. Chuyển đoạn"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Công nghệ gen dựa trên?","options":["A. ADN tái tổ hợp","B. Đột biến tự nhiên","C. Giao phối","D. Chọn lọc tự nhiên"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Plasmid thường có ở?","options":["A. Vi khuẩn","B. Động vật","C. Thực vật","D. Nấm lớn"],"answer":"A","explanation":"Kiến thức SGK."},

{"question":"Sự trao đổi chéo xảy ra giữa?","options":["A. NST không tương đồng","B. NST tương đồng","C. Gen khác loài","D. Ribôxôm"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Đa dạng sinh học cao giúp?","options":["A. Ổn định hệ sinh thái","B. Mất cân bằng","C. Giảm sinh sản","D. Tăng đột biến"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Chọn lọc tự nhiên tác động trực tiếp lên?","options":["A. Kiểu hình","B. Kiểu gen","C. Giao tử","D. ADN"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Tương tác át chế là?","options":["A. Một gen lấn át gen khác","B. Hai gen cùng biểu hiện","C. Không tương tác","D. Đồng trội"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Hệ sinh thái gồm thành phần nào?","options":["A. Vô sinh và hữu sinh","B. Chỉ hữu sinh","C. Chỉ vô sinh","D. Chỉ động vật"],"answer":"A","explanation":"Kiến thức SGK."},

{"question":"Biến dị không di truyền là?","options":["A. Đột biến","B. Thường biến","C. Tái tổ hợp","D. Đa bội"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Cơ sở vật chất của di truyền là?","options":["A. Protein","B. ADN","C. Lipit","D. Gluxit"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Sự phân li của cặp alen xảy ra ở?","options":["A. Giảm phân","B. Nguyên phân","C. Phiên mã","D. Dịch mã"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Hội sinh là quan hệ?","options":["A. Một có lợi, một không hại","B. Cả hai có lợi","C. Cả hai có hại","D. Đối kháng"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Nhân tố tiến hóa làm giảm đa dạng là?","options":["A. Giao phối ngẫu nhiên","B. Phiêu bạt di truyền","C. Đột biến","D. Di nhập gen"],"answer":"B","explanation":"Kiến thức SGK."},

{"question":"Quá trình cố định nitơ do?","options":["A. Vi khuẩn cố định đạm","B. Thực vật","C. Động vật","D. Nấm lớn"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Gen nhảy còn gọi là?","options":["A. Transposon","B. Operon","C. Codon","D. Intron"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Phân tử mang thông tin ra ribôxôm là?","options":["A. rARN","B. tARN","C. mARN","D. ADN"],"answer":"C","explanation":"Kiến thức SGK."},
{"question":"Hiện tượng thoái hóa giống do?","options":["A. Giao phối gần","B. Đột biến có lợi","C. Dị hợp cao","D. Đa bội chẵn"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Tiến hóa là quá trình?","options":["A. Biến đổi quần thể qua thời gian","B. Tăng kích thước cá thể","C. Sinh sản nhanh","D. Tăng ADN"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Áp lực chọn lọc càng mạnh khi?","options":["A. Môi trường ổn định","B. Môi trường biến đổi","C. Không có biến dị","D. Không sinh sản"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Đột biến trung tính có đặc điểm?","options":["A. Không ảnh hưởng rõ rệt","B. Luôn có lợi","C. Luôn có hại","D. Gây chết"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Nguồn nguyên liệu sơ cấp của tiến hóa là?","options":["A. Đột biến","B. Giao phối","C. Chọn lọc","D. Cách li"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Tái tổ hợp gen xảy ra trong?","options":["A. Nguyên phân","B. Giảm phân","C. Phiên mã","D. Dịch mã"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Sự phát sinh loài mới nhanh nhất ở?","options":["A. Cách li địa lí","B. Cách li sinh thái","C. Cách li tập tính","D. Cách li cơ học"],"answer":"A","explanation":"Kiến thức SGK."},

{"question":"Gen có thể bị đột biến do?","options":["A. Tác nhân vật lí, hóa học","B. Nước","C. Oxi","D. Glucozơ"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Sự cân bằng sinh thái được duy trì nhờ?","options":["A. Quan hệ sinh thái","B. Đột biến","C. Nhân đôi","D. Giảm phân"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Chuỗi thức ăn thường có tối đa khoảng?","options":["A. 2 mắt xích","B. 3-5 mắt xích","C. 10 mắt xích","D. 20 mắt xích"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Mối quan hệ cạnh tranh dẫn đến?","options":["A. Phân li ổ sinh thái","B. Đồng tồn tại hoàn toàn","C. Không thay đổi","D. Tăng sinh sản"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Thường biến có đặc điểm?","options":["A. Không di truyền","B. Di truyền","C. Gây đột biến","D. Tăng alen"],"answer":"A","explanation":"Kiến thức SGK."},

{"question":"Di truyền liên kết hoàn toàn khi?","options":["A. Không có hoán vị gen","B. Có trao đổi chéo","C. NST khác nhau","D. Đa bội"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Môi trường ảnh hưởng đến kiểu hình thông qua?","options":["A. Kiểu gen","B. NST","C. Ribôxôm","D. Protein ngoại lai"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Đa bội chẵn thường?","options":["A. Hữu thụ","B. Bất thụ","C. Gây chết","D. Không tồn tại"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Sự phân bố cá thể đồng đều do?","options":["A. Cạnh tranh mạnh","B. Hỗ trợ","C. Ngẫu nhiên","D. Sinh sản nhanh"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Giới hạn trên của nhân tố sinh thái gọi là?","options":["A. Điểm cực thuận","B. Điểm giới hạn trên","C. Ổ sinh thái","D. Cân bằng"],"answer":"B","explanation":"Kiến thức SGK."},

{"question":"Sự hình thành đặc điểm thích nghi do?","options":["A. Chọn lọc tự nhiên","B. Đột biến có hại","C. Ngẫu nhiên hoàn toàn","D. Không biến dị"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Cơ chế cách li trước hợp tử gồm?","options":["A. Cách li tập tính","B. Con lai bất thụ","C. Con lai chết","D. Giảm sức sống"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Cơ chế cách li sau hợp tử gồm?","options":["A. Tập tính khác","B. Con lai bất thụ","C. Sinh thái khác","D. Thời gian khác"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Tính trạng số lượng thường do?","options":["A. Một gen","B. Nhiều gen","C. Một alen","D. NST giới tính"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Hệ sinh thái nhân tạo phụ thuộc nhiều vào?","options":["A. Con người","B. Tự nhiên","C. Đột biến","D. Chọn lọc"],"answer":"A","explanation":"Kiến thức SGK."},

{"question":"Di nhập gen làm thay đổi?","options":["A. Tần số alen","B. Kiểu hình cá thể","C. Số NST","D. Mã di truyền"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Đột biến có hại vẫn tồn tại do?","options":["A. Lặn","B. Trội hoàn toàn","C. Không di truyền","D. Không biểu hiện"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Đa dạng loài cao giúp hệ sinh thái?","options":["A. Kém ổn định","B. Ổn định hơn","C. Dễ sụp đổ","D. Giảm năng lượng"],"answer":"B","explanation":"Kiến thức SGK."},
{"question":"Sự phân li kiểu gen trong quần thể do?","options":["A. Giao phối","B. Hô hấp","C. Quang hợp","D. Tiêu hóa"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Tiến hóa nhỏ kết thúc khi?","options":["A. Hình thành loài mới","B. Tăng kích thước","C. Tăng ADN","D. Không sinh sản"],"answer":"A","explanation":"Kiến thức SGK."},
{"question":"Một gen có chiều dài 5100 Å. Số cặp nu của gen là bao nhiêu?","options":["A. 1500","B. 3000","C. 4500","D. 6000"],"answer":"A","explanation":"1 cặp nu dài 3,4 Å → 5100/3,4 = 1500 cặp nu."},

{"question":"Một gen có 2400 nu. Số liên kết hiđrô tối đa khi gen có 60% G-X là?","options":["A. 3120","B. 3600","C. 3840","D. 4200"],"answer":"C","explanation":"G-X chiếm 60% → 1440 nu G+X → 720 cặp G-X (3H) và 480 cặp A-T (2H) → 720×3 + 480×2 = 3840."},

{"question":"Ở phép lai AaBb × AaBb, số kiểu gen tối đa ở đời con là?","options":["A. 4","B. 9","C. 16","D. 10"],"answer":"B","explanation":"Mỗi cặp gen cho 3 kiểu gen → 3×3 = 9."},

{"question":"Một quần thể có tần số alen A = 0,7. Theo Hardy–Weinberg, tần số kiểu gen aa là?","options":["A. 0,49","B. 0,21","C. 0,09","D. 0,3"],"answer":"C","explanation":"q = 0,3 → aa = q² = 0,09."},

{"question":"Một loài có bộ NST 2n = 24. Số NST trong thể ba là?","options":["A. 23","B. 24","C. 25","D. 26"],"answer":"C","explanation":"Thể ba: 2n + 1 = 25."},

{"question":"Trong giảm phân, nếu 1 cặp NST không phân li ở giảm phân I thì giao tử có số NST?","options":["A. n","B. n+1 hoặc n-1","C. 2n","D. 2n+1"],"answer":"B","explanation":"Không phân li tạo giao tử n+1 và n-1."},

{"question":"Ở phép lai phân tích AaBb (phân li độc lập), tỉ lệ kiểu hình là?","options":["A. 1:1","B. 1:1:1:1","C. 3:1","D. 9:3:3:1"],"answer":"B","explanation":"Lai AaBb × aabb → 4 tổ hợp bằng nhau."},

{"question":"Một gen sau đột biến mất 3 cặp nu. Hậu quả có thể là?","options":["A. Mất 1 axit amin","B. Lệch khung đọc","C. Không dịch mã","D. Tăng 1 axit amin"],"answer":"A","explanation":"Mất bội số 3 không làm lệch khung đọc → mất 1 aa."},

{"question":"Nếu p = 0,6 và quần thể cân bằng, tần số dị hợp là?","options":["A. 0,36","B. 0,48","C. 0,16","D. 0,24"],"answer":"B","explanation":"2pq = 2×0,6×0,4 = 0,48."},

{"question":"Một chuỗi polipeptit gồm 199 axit amin. Số nu trên mARN mã hóa (không tính bộ ba kết thúc) là?","options":["A. 597","B. 600","C. 603","D. 594"],"answer":"A","explanation":"199 × 3 = 597 nu."},

{"question":"Trong hệ sinh thái, hiệu suất sinh thái trung bình khoảng?","options":["A. 1%","B. 10%","C. 50%","D. 90%"],"answer":"B","explanation":"Hiệu suất truyền năng lượng khoảng 10%."},

{"question":"Ở phép lai Aa × Aa, xác suất thu được cá thể dị hợp là?","options":["A. 25%","B. 50%","C. 75%","D. 100%"],"answer":"B","explanation":"Tỉ lệ 1AA:2Aa:1aa → dị hợp 2/4 = 50%."},

{"question":"Nếu quần thể có 1000 cá thể với 160 cá thể aa, tần số alen a là?","options":["A. 0,4","B. 0,2","C. 0,16","D. 0,8"],"answer":"A","explanation":"aa = 0,16 → q = √0,16 = 0,4."},

{"question":"Một gen có 900 cặp nu. Số vòng xoắn của gen là?","options":["A. 45","B. 60","C. 90","D. 100"],"answer":"C","explanation":"1 vòng xoắn = 10 cặp nu → 900/10 = 90."},

{"question":"Trong quần thể cân bằng, nếu q = 0,2 thì tần số alen trội p là?","options":["A. 0,2","B. 0,4","C. 0,6","D. 0,8"],"answer":"D","explanation":"p + q = 1 → p = 0,8."}
]
